### ISSUE TITLE
Latest release includes dependencies of UnitTesting module

### ISSUE THREAD

**Issue by reinouts** [WebFlight/Queue#18]
Modules should contain only their own dependencies, but the latest release also includes dependencies belonging to the UnitTesting module (and three different versions of the JUnit4 library even!)

If the reason for this is to support compilation of the Test java classes, I suggest not to include them in the distribution package of the Queue module. If people want to run the unit tests against the Queue module, they can install the UnitTesting module themselves. 

![Capture](https://user-images.githubusercontent.com/1968692/117626557-870e0680-b177-11eb-8a94-49c0cee67de0.PNG)

**Comment by JaapvanLeeuwen** [comment]
My bad! I fixed it and will publish a new release soon!
