### ISSUE TITLE
Is this offline-capable?

### ISSUE THREAD

**Issue by sjeefr** [WebFlight/Queue#3]
We're working on an offline app, since the all-time online app has issues with connectivity, as it's often used outside in bad cellular regions. The upload of data can often take up to 7 minutes, so we're looking for a way to do the upload in the background, without the app being on screen. Is it possible to queue the synchronization back to the server in the background (and have it retry when unsuccessful) using nanoflows (since only option in offline hybrid apps)?

**Comment by mennodehaas** [comment]
Thanks for your message. I will limit my answer to the scope of this repo. The Queue module is written in Java and works on the Mendix backend running inside a JVM. This means, the module does not interact with front-end components and cannot be used without backend communication. If you would like to use data sync options, you could look into the new Mendix ReactNative functionalities: https://docs.mendix.com/refguide/offline-first
If this does not solve your issues, you need to look outside of Mendix (other libraries that may solve your issues or go for custom mobile with something like AWS AppSync).
