### ISSUE TITLE
Double(double) in Double has been deprecated

### ISSUE THREAD

**Issue by reinouts** [WebFlight/Queue#6]
When building our project with the Queue module, I get the following warning: 

```
ExponentialBackoffCalculator.java:6: warning: [deprecation] Double(double) in Double has been deprecated
                Double exponentialBackOff = new Double(Math.round(base * Math.pow(2, retry)));
```

It is recommended to use `Double.valueOf(double)` instead.

https://github.com/WebFlight/Queue/blob/f1f185dca30f77c13ba2ffa3649d9b802c167048/javasource/queue/helpers/ExponentialBackoffCalculator.java#L6

**Comment by mennodehaas** [comment]
Already fixed that one for the next version release.
