### ISSUE TITLE
Small remark for the documentation

### ISSUE THREAD

**Issue by BartReyserhove** [WebFlight/Queue#7]
I was a little bit confused by the following sentence in the documentation: 

> The AddJobToQueue action will add a new job in a queue that has been initialized before. Make sure the microflow to be executed as an input parameter with data type Object and entity Queue.Job or an entity that has Queue.Job as a Generalization

I think it should be

`The AddJobToQueue action will add a new job in a queue that has been initialized before. Make sure the microflow to be executed **has** an input parameter with data type Object and entity Queue.Job or an entity that has Queue.Job as a Generalization`

I know, really minor remark ;-) Great module by the way

**Comment by mennodehaas** [comment]
@BartReyserhove Thanks for your comments, just merged the changed in the README.
