### ISSUE TITLE
Timezone setting not DST compatible

### ISSUE THREAD

**Issue by jeroen-huizer-conclusion** [WebFlight/Queue#8]
The TIMEZONE_ID constant does not set the timezone with which the microflow is executed, instead it applies an offset to UTC.
The result is that DST is not correctly applied in the microflow.

The following screenshots show the problem.
Default timezone and queue timezone are set to Europe/Amsterdam (GMT+1).
Note that Jan 1 00:00 datetime is handled correctly (+1 is applied), but the Jun 1 00:00 datetime is not handled correctly (+1 is applied, while +2 is applicable according to DST).

Setting:
![timezone_setting](https://user-images.githubusercontent.com/21953339/86094208-8238ea80-bab0-11ea-90a1-6b24d276f108.png)

Queue:
![timezone_queue](https://user-images.githubusercontent.com/21953339/86093779-d1cae680-baaf-11ea-8e8d-64c5c430f515.png)

Scheduled event:
![timezone_sce](https://user-images.githubusercontent.com/21953339/86095654-8c5be880-bab2-11ea-83d4-bc7446a0acfd.PNG)

User:
![timezone_session](https://user-images.githubusercontent.com/21953339/86093769-cd9ec900-baaf-11ea-90c4-8a6382684ae6.png)

The problem is that the setTimezone method in [JobToQueueAdder ](https://github.com/WebFlight/Queue/blob/master/javasource/queue/helpers/JobToQueueAdder.java)does not override timezone, but adds a raw offset to the UTC timezone. Unfortunately I can offer no solution, hopefully you can find one, or update the documentation.

P.s.: though this cost me some headache, I enjoy using the Queue module, it is a major improvement in ease of use and performance compared to the platform version. Thanks!

**Comment by mennodehaas** [comment]
Hi @jeroen-huizer-conclusion thanks for letting me know! I will have a look soon when I prepare a new update.

**Comment by JaapvanLeeuwen** [comment]
@jeroen-huizer-conclusion I just released an update which fixes this issue! Simply configure the USEDST_IFAPPLICABLE constant and you should be good to go!

**Comment by jeroen-huizer-conclusion** [comment]
@JaapvanLeeuwen I finally got around to testing this. 
It does not work as expected and still differs from the DST handling in SCE and user sessions.

It appears as if the extra DST offset is now always applied; see attached screenshot.
This will work for [%CurrentDateTime%], but not for datetimes in general.

![Screenshot 2021-09-23 084751](https://user-images.githubusercontent.com/21953339/134465715-0dce8479-1c81-423d-a038-0296a77653a1.png)
